DROP TABLE EMP1;
DROP TABLE EMP_MGR_ENGR;
DROP TABLE EMP_TRAINEE;

CREATE TABLE EMP1(
    ID NUMBER(2),
    Name VARCHAR2(10),
    Basic NUMBER(6,2),
    Designation VARCHAR2(10),
    Age NUMBER(2)
);
DESC EMP1;

ALTER TABLE EMP1 
MODIFY(Basic NUMBER (6));
DESC EMP1;

ALTER TABLE EMP1
MODIFY (Name VARCHAR2(15));
DESC EMP1;

CREATE TABLE EMP_TRAINEE AS
SELECT ID AS Emp_id,Name,Basic,Designation,Age
FROM EMP1
where 1=2;
DESC EMP_TRAINEE;

INSERT INTO EMP1 VALUES(1,'Rohit',6700,'Manager',24);
INSERT INTO EMP1 VALUES(2,'Sunil',6200,'Engineer',27);
INSERT INTO EMP1 VALUES(3,'Payal',6300,'Engineer',25);
INSERT INTO EMP1 VALUES(4,'Kunal',6700,'Trainee',28);
INSERT INTO EMP1 VALUES(5,'Sunita',6230,'Trainee',26);
INSERT INTO EMP1 VALUES(6,'Bimal',7000,'Trainee',25);
COMMIT;

INSERT INTO EMP_TRAINEE (Emp_id,Name,Basic,Designation,Age)
SELECT ID, Name,Basic,Designation,Age
FROM EMP1
WHERE Designation = 'Trainee';

ALTER TABLE EMP1
ADD(Skills VARCHAR2(10),DOJ DATE);

UPDATE EMP1 
SET Skills ='SQL' , DOJ= TO_DATE('08-JAN-2006','DD-MON-YYYY');

UPDATE EMP1
SET Basic = Basic+500
WHERE Designation = 'Engineer';

ALTER TABLE EMP1
RENAME COLUMN Age TO Age_in_Years;

ALTER TABLE EMP_TRAINEE
DROP COLUMN Age;

RENAME EMP1 TO EMP_Mgr_Engr;

TRUNCATE TABLE EMP_Mgr_Engr;
COMMIT;

UPDATE EMP1
SET Designation = 'Engineer'
WHERE NAME ='Payal';
COMMIT;

UPDATE EMP1 SET BASIC = 6700 WHERE Name = 'Sunil';
UPDATE EMP1 SET BASIC = 6800 WHERE Name = 'Payal';



